# Generated by Django 3.0.3 on 2020-02-23 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('interested_fields', models.TextField()),
                ('amount_to_invest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('place', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seekers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('skill_set', models.TextField()),
                ('years_of_experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StartUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('siteurl', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('compEmail', models.EmailField(max_length=1000)),
                ('regID', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('skill_set', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.StartUps')),
            ],
        ),
        migrations.CreateModel(
            name='Investment_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('day_invested', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.Investors')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.StartUps')),
            ],
        ),
    ]
