# Generated by Django 3.0.3 on 2020-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0003_auto_20200223_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='website',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
